---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,F,T,T,F)
class(aLogical)
sum(aLogical)
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
studentMajor <- factor(c('經濟系','經濟系','法律系'))
```
```{r}
studentMajor0 <- (c('經濟系','經濟系','法律系'))
```

```{r}
studentMajors <- factor(c("經濟系", "經濟系", "法律系"))
```

```{r}
class(studentMajor)
typeof(studentMajor)
```
```{r}
as.integer(studentMajor)
```

```{r}
birth_place <- factor(c('台北市','桃園市','屏東市','台北市'))
typeof(birth_place)
as.integer(birth_place)
```

```{r}
birth_place2 <- (c('台北市','桃園市','屏東市'))
typeof(birth_place2)
```

```{r}
birth_place2 <- (c('台北市','桃園市','屏東市'))

typeof(birth_place2)
as.integer(birth_place2)
```

```{r}
birth_place2 <- c('台北市','桃園市','屏東市')
birth_place2 <- as.integer(birth_place2)
typeof(birth_place2)
as.integer(birth_place2)
```
```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22"))
```

```{r}
class(dtObject)
```

```{r}
dtObject
```
```{r}
typeof(dtObject)
```
```{r}
Sys.timezone()
```

