---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,F,T,T,F)
class(aLogical)
sum(aLogical)
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
studentMajor <- factor(c('經濟系','經濟系','法律系'))
```
```{r}
studentMajor0 <- (c('經濟系','經濟系','法律系'))
```

```{r}
studentMajors <- factor(c("經濟系", "經濟系", "法律系"))
```

```{r}
class(studentMajor)
typeof(studentMajor)
```
```{r}
as.integer(studentMajor)
```

```{r}
birth_place <- factor(c('台北市','桃園市','屏東市','台北市'))
typeof(birth_place)
as.integer(birth_place)
```

```{r}
birth_place2 <- (c('台北市','桃園市','屏東市'))
typeof(birth_place2)
```

```{r}
birth_place2 <- (c('台北市','桃園市','屏東市'))

typeof(birth_place2)
as.integer(birth_place2)
```

```{r}
birth_place2 <- c('台北市','桃園市','屏東市')
birth_place2 <- as.integer(birth_place2)
typeof(birth_place2)
as.integer(birth_place2)
```
```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22"))
```

```{r}
class(dtObject)
```

```{r}
dtObject
```
```{r}
typeof(dtObject)
```
```{r}
Sys.timezone()
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
```
```{r}
twDateTime <- mdy_hms("3/14/2019 8:18:47", tz="Asia/Taipei")
twDateTime
```
```{r}
twDateTime2 <- mdy("March, 1, 2019")
twDateTime2
```
```{r}
LisbonDateTime <- ymd("2018-09-11")
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)

a+bL
aL+bL
aL*b
a+4
```
```{r}
a+b
a/b
a%%b
```
```{r}
startingDate <- ymd("2000-02-17")
startingDate2 <- ymd("2001-05-20")
startingDate + years(1)
startingDate + dyears(1)
```
```{r}
startingDate - startingDate2
```
```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)

x==y
x>y
x<y

x2==y2
x2>y2
x2<y2
```
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")

x3!=y3
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2==y2
```
```{r}
x2
is.na(x2)
sum(x2)
sum(x2,na.rm = F)
sum(x2,na.rm = T)
 #設定為Ｔ以忽略ＮＡ
```
```{r}
0/0
0%%0
0**0
```
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```
```{r}
head(currency)
```
```{r}
class(currency)#非類別資料factor
```


```{r}
levels(currency)
```
```{r}
currency <- as.factor(currency)
class(currency)
levels(currency)
```
```{r}
length(levels(currency))#屬向量內元素的個數
```
```{r}
step1_extratLevelsVector <- levels(currency)
step1_extratLevelsVector
```
```{r}
step2_countVectorLength <- length(step1_extratLevelsVector)
step2_countVectorLength
```
```{r}
currency2 <- c("日圓", "美元","日元")
currency2
```
```{r}
sum(currency2 == "日元")
```
```{r}
head(currency)
sum(currency == "日圓JPY/USD")
```
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```
```{r}
!(x5 %in% greatTaipei)
```
```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```
```{r}
x5 %in% greatTaipei
y5 == "女"
(x5 %in% greatTaipei) & (y5 == "女")
```
```{r}
which((x5 %in% greatTaipei)&(y5=="女"))
```
```{r}
x5
y5
(x5 %in% greatTaipei)
(y5 == "女")
(x5 %in% greatTaipei) | (y5 == "女")
```
```{r}
which((x5 %in% greatTaipei)| (y5 == "女"))
```
```{r}
x5 %in% greatTaipei
y5 == "女"
xor(x5 %in% greatTaipei, y5 == "女")
```
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
```{r}
class(date)
head(date)
```
```{r}
library(lubridate)
date <- ymd(date)
```

```{r}
class(date)
```
1980-08-01之後的資料有多少筆
```{r}
isAfter19800801 <-
  date >= ymd("1980-08-01")
isAfter19800801
```
```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))
```
```{r}
class(isAfter19800801)
```
```{r}
sum(isAfter19800801)
```



引入套件
```{r}
library(stringr)
```

```{r}
now <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
browseURL("https://www.ntpu.edu.tw")
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```
```{r}
demand_supply_fun<- function(P,a,b,c,d){
  Qs <- a+b*P
  Qd <- c-d*P
  return(
    list(供給量=Qs,
        需求量=Qd,
        超額供給量=Qs-Qd))
}
```

```{r}
gpa_fun <- function(studentID){

  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent

    subSample <- transcriptDataFinal[logiChosenStudent,]

    sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
    return(GPA)
  }else{
    message("查無此學號")

 }
}
```

```{r}
fizzbuzz <- function(num){
  if (num %% 3 == 0){return('Fizz')}
  else if (num %% 5 == 0){return('Bizz')}
  else if (num %% 3 == 0 & num %% 5 == 0){return('fizzbuzz')}
  else {return('num')}
}
```

```{r}
fizzbuzz(50)
```




