---
title: '123'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
```



```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`????????????????????????????????????`
major <- transcriptDataFinal$??????
studentID <- transcriptDataFinal$??????
grade <- transcriptDataFinal$????????????
```

```{r}
course <- c("???????????????","?????????","???????????????")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
studentID
?????? <- str_sub(studentID,5,6)
????????? <- str_sub(studentID,2,4)
```
```{r}
str_subset(course,"?????????")
```
```{r}
str_detect(course,"?????????")
```
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("???","???","???")
char2 <- c("???","???","???")
month
char1
day 
char2
str_c(month,char1,day,char2)
```
```{r}
str_c(month,c("???"),day,c("???"))
str_c(month,"???",day,"???")
```
```{r}
month
day
str_c(month,day, sep="-")
```
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates
str_replace(dates,"-","???")
```
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("https://github.com",username,reponame,sep="/")
```

