---
title: '123'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
```



```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
studentID
系號 <- str_sub(studentID,5,6)
入學年 <- str_sub(studentID,2,4)
```
```{r}
str_subset(course,"經濟學")
```
```{r}
str_detect(course,"經濟學")
```
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```
```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```
```{r}
month
day
str_c(month,day, sep="-")
```
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates
str_replace(dates,"-","月")
```
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("https://github.com",username,reponame,sep="/")
```







練習一
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```
```{r}
birthday
```
```{r}
y = str_sub(birthday,1,4)
m = str_sub(birthday,5,6)
d = str_sub(birthday,7,8)
dd = str_c("西元",y,"年",m,"月",d,"日")
dd
```
```{r}
民國年月<-c("099/01","099/02","099/03")
```
```{r}
class(民國年月)
```
```{r}
Y=str_sub(民國年月,2,3)
M=str_sub(民國年月,5,6)
Y=as.numeric(Y)
Y=Y+1911
str=str_c("西元",Y,"年",M,"月")
str
```

```{r}
a<-c(1:3)
typeof(a)
a
```
```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(a)
aWithNames
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```
[[.]]
```{r}
plasticContainer

plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```


```{r}
your_github_username <- "SheeperISme"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```

```{r}
commitCheckStatement
```

```{r}
commitCheck
```

```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1

class(Mat1)
typeof(Mat1)
```
```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```
```{r}
m2<-matrix(c("a","b","c","d"),2,2)
class(m2)
typeof(m2)
a<-m2[[1]]
c<-m2[[3]]
bd<-m2[2,]
a
c
bd
```
```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```
```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```
```{r}
StuDF
StuDF[['姓名']][[3]]
StuDF[[2]][[3]]
```
```{r}
class(StuDF$姓名)
typeof(StuDF$姓名)
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```
```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```


```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
chosenLETTERS2 <- LETTERS[1:8]
matObj0 <- matrix(chosenLETTERS2,4,2)
tolower(matObj0)
chosenLETTERS2
matObj0
```
```{r}
chosenLETTERS[8]
matObj1[8]
```
```{r}
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```
```{r}
StuDF
StuDF[c("姓名","成績")] 
StuDF[1:5,c("姓名","成績")] 
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
classSurvey[,c(4,5)]
```

```{r}
classSurvey[,c(4)=='女']
```
```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```
```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```
```{r}
matObj1
```
```{r}
colnames(matObj1) 
rownames(matObj1)
```
```{r}
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1
```
```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b[c(3,5)] <- c('False','7')
b
```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)

isAsiaCrisis <- (exData3$期間 >= ymd(1997-06-01) & 
  exData3$期間 <= ymd(1998-12-01))
```
```{r}
a <-as.double(ymd("1997-06-01"))
b <-as.double(ymd("1998-12-01"))
dou <- as.double(exData3$期間) 
isAsiaCrisis <- (dou-a) >=0 & (b-dou)<=0
isAsiaCrisis
```
```{r}

```
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  sum(transcriptDataFinal$學期成績[logiChosenStudent]*
    transcriptDataFinal$學分數[logiChosenStudent])/
    sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
  return(GPA)
}
```
```{r}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```
```{r}
studentID <-"92aS67fee" 
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
gpa_fun(studentID) # 使用global environmen裡物件studentID的值當輸入值
gpa_fun("92aS67fee")
```
```{r}
plus<- function(x,alpha){
  plusValue <- x + alpha # 程序產生output值
  return(plusValue) # 傳回output值
}
```
```{r}
plus(50,8828)
```
```{r}
supply_fun<- function(a,b,P){
  Qs <- a+b*P # 程序產生output值
  return(Qs) # 傳回output值
}
supply_fun(1,222,exp(5))
```
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent

subSample <- transcriptDataFinal[logiChosenStudent,]

sum(subSample$學期成績*subSample$學分數)/
  sum(subSample$學分數) -> GPA
```
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tz=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

```{r}
print('a')
```

